pool:
  vmImage: "ubuntu-16.04"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.7
      architecture: "x64"

  - script: |
      pip install -e .
    displayName: "Install prerequisites"

  - script: |
      python setup.py -q test
    condition: succeededOrFailed()
    displayName: "Run tests"

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: "**/test-*.xml"
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "**/coverage.xml"
      reportDirectory: "**/htmlcov"
    condition: succeededOrFailed()

  - script: |
      docker build -t $DOCKER_REGISTRY.azurecr.io/${BUILD_REPOSITORY_NAME##*/}:${BUILD_SOURCEVERSION} .
      docker tag $DOCKER_REGISTRY.azurecr.io/${BUILD_REPOSITORY_NAME##*/}:${BUILD_SOURCEVERSION} $DOCKER_REGISTRY.azurecr.io/${BUILD_REPOSITORY_NAME##*/}:latest
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY.azurecr.io
      docker push $DOCKER_REGISTRY.azurecr.io/${BUILD_REPOSITORY_NAME##*/}
    env:
      DOCKER_PASSWORD: $(docker.password)
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: "Build and push Docker image"
    enabled: false
